# Generated by Django 5.1.7 on 2025-07-22 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0021_secondrywarehouserawmaterial_item_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('is_sub', models.BooleanField(default=False)),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catgory', to='warehousing.category', verbose_name='زیر دسته بندی')),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterialwarehouse',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='warehousing.category'),
        ),
    ]
