# Generated by Django 5.1.7 on 2025-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0022_category_rawmaterialwarehouse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinewarehouse',
            name='category',
            field=models.ManyToManyField(blank=True, to='warehousing.category'),
        ),
    ]
