# Generated by Django 5.1.7 on 2025-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0023_quarantinewarehouse_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_rel', to='warehousing.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
