# Generated by Django 5.1.7 on 2025-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0025_alter_category_options_alter_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_rel_raw', to='warehousing.category', verbose_name='دسته\u200cبندی'),
        ),
    ]
