# Generated by Django 5.1.7 on 2025-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0026_alter_rawmaterialwarehouse_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowedproduct',
            options={'verbose_name': 'امانی از شرکت دیگر', 'verbose_name_plural': 'امانی از شرکت دیگر'},
        ),
        migrations.AlterModelOptions(
            name='externalproductdelivery',
            options={'verbose_name': 'امانی شرکت به بیرون', 'verbose_name_plural': 'امانی شرکت به بیرون'},
        ),
        migrations.AlterModelOptions(
            name='returnedfromcustomer',
            options={'verbose_name': 'محصول برگشتی شرکت توسط کارفرما', 'verbose_name_plural': 'محصول برگشتی شرکت توسط کارفرما'},
        ),
        migrations.AddField(
            model_name='externalproductdelivery',
            name='reference_letter',
            field=models.BooleanField(default=True, verbose_name='معرفی نامه دارد؟'),
        ),
    ]
