# Generated by Django 5.1.7 on 2025-07-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0027_alter_borrowedproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinewarehouse',
            name='Meterage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='(متر)متراژ'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
    ]
