# Generated by Django 5.1.7 on 2025-08-31 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0028_quarantinewarehouse_meterage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproductdelivery',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تحویل دهنده'),
        ),
        migrations.AlterField(
            model_name='externalproductdeliveryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productwarehouse', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='externalproductdeliveryrawmaterial',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.rawmaterialwarehouse', verbose_name='ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='externalproductdeliverysecondryproduct',
            name='secondry_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.secondrywarehouse', verbose_name='محصول ثانویه'),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='productdelivery',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تحویل دهنده'),
        ),
        migrations.AlterField(
            model_name='productdeliveryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productwarehouse', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productdeliveryrawmaterial',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.rawmaterialwarehouse', verbose_name='ماده اولیه'),
        ),
        migrations.AlterField(
            model_name='productdeliverysecondryproduct',
            name='secondry_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.secondrywarehouse', verbose_name='محصول ثانویه'),
        ),
        migrations.AlterField(
            model_name='productpart',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='raw_material_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.rawmaterialwarehouse', verbose_name='انتخاب از انبار مواد اولیه'),
        ),
        migrations.AlterField(
            model_name='productsecondryproduct',
            name='secondry_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.secondrywarehouse', verbose_name='محصول ثانویه مصرف\u200cشده'),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='qc_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.responsibleforqc', verbose_name='مسئول QC'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='test_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.responsiblefortesting', verbose_name='مسئول تست'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='rawmaterialwarehouse',
            name='quarantine_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.quarantinewarehouse', verbose_name='ارجاع به قرنطینه'),
        ),
        migrations.AlterField(
            model_name='responsibleforqc',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='responsiblefortesting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='returnedfromcustomer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='returnedproduct',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='secondrywarehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AlterField(
            model_name='secondrywarehouserawmaterial',
            name='raw_material_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.rawmaterialwarehouse', verbose_name='انتخاب از انبار مواد اولیه'),
        ),
    ]
