# Generated by Django 5.1.7 on 2025-09-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0029_alter_externalproductdelivery_deliverer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdeliveryrawmaterial',
            options={'verbose_name': 'مواد اولیه انبار ثانویه', 'verbose_name_plural': 'مواد اولیه انبار ثانویه'},
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='raw_material_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود ماده اولیه'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='raw_material_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ماده اولیه'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='raw_material_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت ماده اولیه'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='unit',
            field=models.CharField(blank=True, choices=[('dollar', 'دلار'), ('toman', 'تومان')], max_length=50, null=True, verbose_name='واحد'),
        ),
        migrations.AddField(
            model_name='productdeliveryrawmaterial',
            name='user_who_used',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='استفاده کننده'),
        ),
        migrations.AlterField(
            model_name='productdeliveryrawmaterial',
            name='quantity',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='status',
            field=models.CharField(choices=[('waiting_test', 'در انتظار تست'), ('testing', 'در حال تست'), ('testing_done', 'تست شده'), ('qc_pending', 'در انتظار QC'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('transferred', 'منتقل شده'), ('used_in_product', 'استفاده شده در محصول'), ('used_in_secondry_warehouse', 'استفاده شده در انبار ثانویه'), ('inCompany', 'تحویل افراد شرکت')], default='waiting_test', max_length=50, verbose_name='وضعیت قطعه'),
        ),
    ]
