# Generated by Django 5.1.7 on 2025-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0030_alter_productdeliveryrawmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdeliveryproduct',
            options={'verbose_name': 'محصولات تحویل افراد', 'verbose_name_plural': 'محصولات تحویل افراد'},
        ),
        migrations.AlterModelOptions(
            name='productdeliveryrawmaterial',
            options={'verbose_name': 'مواد اولیه تحویل افراد', 'verbose_name_plural': 'مواد اولیه تحویل افراد'},
        ),
        migrations.AlterModelOptions(
            name='productdeliverysecondryproduct',
            options={'verbose_name': 'محصولات ثانویه تحویل افراد', 'verbose_name_plural': 'محصولات ثانویه تحویل افراد'},
        ),
        migrations.AlterField(
            model_name='quarantinewarehouse',
            name='status',
            field=models.CharField(choices=[('waiting_test', 'در انتظار تست'), ('testing', 'در حال تست'), ('testing_done', 'تست شده'), ('qc_pending', 'در انتظار QC'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('transferred', 'موجود در انبار اولیه'), ('used_in_product', 'استفاده شده در محصول'), ('used_in_secondry_warehouse', 'استفاده شده در انبار ثانویه'), ('inCompany', 'تحویل افراد شرکت'), ('outCompany', 'امانی شرکت به بیرون')], default='waiting_test', max_length=50, verbose_name='وضعیت قطعه'),
        ),
    ]
