# Generated by Django 5.1.7 on 2025-09-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0031_alter_productdeliveryproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductdeliveryrawmaterial',
            name='raw_material_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ماده اولیه'),
        ),
    ]
