# Generated by Django 5.1.7 on 2025-09-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0032_externalproductdeliveryrawmaterial_raw_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdeliveryrawmaterial',
            name='raw_material_entry_date',
        ),
        migrations.AddField(
            model_name='externalproductdeliveryrawmaterial',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productcode', verbose_name='کد کالا'),
        ),
        migrations.AddField(
            model_name='externalproductdeliveryrawmaterial',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehousing.productpart', verbose_name='پارت کالا'),
        ),
        migrations.AddField(
            model_name='externalproductdeliveryrawmaterial',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره سریال'),
        ),
    ]
