# Generated by Django 5.1.7 on 2025-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0033_remove_productdeliveryrawmaterial_raw_material_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwarehouse',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='status',
            field=models.CharField(choices=[('product_warehouse', 'انبار محصولات'), ('internal_product', 'تحویل افراد درون شرکت'), ('out_product', 'امانی به خارج از شرکت'), ('seller_product', 'فروخته شده'), ('approved', 'تایید شده')], default='product_warehouse', max_length=50, verbose_name='وضعیت محصول'),
        ),
    ]
