# Generated by Django 5.1.7 on 2025-09-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0034_productwarehouse_quantity_productwarehouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwarehouse',
            name='status',
            field=models.CharField(choices=[('product_warehouse', 'انبار محصولات'), ('internal_product', 'تحویل افراد درون شرکت'), ('out_product', 'امانی شرکت به بیرون'), ('seller_product', 'فروخته شده')], default='product_warehouse', max_length=50, verbose_name='وضعیت محصول'),
        ),
    ]
