# Generated by Django 5.1.7 on 2025-09-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0035_alter_productwarehouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsecondryproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='تعداد مصرف\u200c شده از محصول ثانویه'),
        ),
    ]
