# Generated by Django 5.1.7 on 2025-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0037_secondrywarehouse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondrywarehouse',
            name='status',
            field=models.CharField(choices=[('secondry_warehouse', 'انبار ثانویه'), ('in_product', 'استفاده شده در محصول'), ('internal_product', 'تحویل افراد درون شرکت'), ('out_product', 'امانی شرکت به بیرون'), ('seller_product', 'فروخته شده')], default='secondry_warehouse', max_length=50, verbose_name='وضعیت محصول'),
        ),
    ]
