# Generated by Django 5.1.7 on 2025-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousing', '0038_alter_secondrywarehouse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantinewarehouse',
            name='status_amani',
            field=models.CharField(choices=[('YES', 'امانی هست'), ('NO', 'امانی نیست')], default='NO', max_length=50, verbose_name='وضعیت امانی'),
        ),
    ]
